### ISSUE TITLE
Does the comments-count work in the homepage?

### ISSUE THREAD

**Issue by cokePanda** [nadjetey/wangana#11]
I saw that index.html keeps a zero over there, so the comments-count is not passed on from disqus？

btw, thanks for your reply to my previous question which I had no time to check out on vacation.

**Comment by nadjetey** [comment]
```html
<a href="{{ post.url | prepend: site.url }}#disqus_thread">0 
```
In the index.html keeps the zero as a placeholder text. It replaces the number with the correct count after fetching results from the Disqus servers. Read here for more details https://help.disqus.com/customer/portal/articles/565624-adding-comment-count-links-to-your-home-page

**Comment by cokePanda** [comment]
got it.
thanks
