### ISSUE TITLE
Here is an issue when the yml url is on local directory

### ISSUE THREAD

**Issue by kenchowcn** [nadjetey/wangana#12]
In Navigation the archive, contact, search, tags are generated by JEKYLL are directories, not a suffix with html pages, there is no problem in the original version, because of the URL in original config.yml is a URL path, when change it to local path, it doesn't work any more, which is not convenient when debug on local PC.

# _includes/sidenav.html

    <li><a href="{{ "/index.html" | prepend: site.url }}">Home</a></li>
    <li><a href="{{ "/archive.html" | prepend: site.url }}">Archive</a></li>
    <li><a href="{{ "/contact.html" | prepend: site.url }}">Contact</a></li>
    <li><a href="{{ "/feed.xml" | prepend: site.url }}">Feed</a></li>    
    <li><a href="{{ "/search.html" | prepend: site.url }}">Search</a></li>
    <li><a href="{{ "/tags.html" | prepend: site.url }}">Tags</a></li>

# fixed:
    <li><a href="{{ "/index.html" | prepend: site.url }}">Home</a></li>
    <li><a href="{{ "/archive/" | prepend: site.url }}">Archive</a></li>
    <li><a href="{{ "/contact/" | prepend: site.url }}">Contact</a></li>
    <li><a href="{{ "/feed.xml" | prepend: site.url }}">Feed</a></li>    
    <li><a href="{{ "/search/" | prepend: site.url }}">Search</a></li>
    <li><a href="{{ "/tags/" | prepend: site.url }}">Tags</a></li>

# tree _site

<pre>
kens-MacBook:_site kenchow$ tree
.
├── 2014
│   └── 03
│       ├── archived-post-example
│       │   └── index.html
│       ├── code-syntax
│       │   └── index.html
│       ├── example-1
│       │   └── index.html
│       ├── example-2
│       │   └── index.html
│       ├── example-3
│       │   └── index.html
│       ├── example-4
│       │   └── index.html
│       ├── example-5
│       │   └── index.html
│       ├── example-6
│       │   └── index.html
│       ├── example-7
│       │   └── index.html
│       ├── example-8
│       │   └── index.html
│       ├── hello-world
│       │   └── index.html
│       ├── post-template
│       │   └── index.html
│       └── typography
│           └── index.html
├── 404
│   └── index.html
├── archive
│   └── index.html
├── contact
│   └── index.html
├── favicon.png
├── feed.xml
├── index.html
├── search
│   └── index.html
├── search.json
├── sitemap.xml
└── tags
    └── index.html
 </pre>

**Comment by kenchowcn** [comment]
When I deployed on github, I need change it back. Do you have any good solutions for this? I am not familiar with ruby things.

**Comment by nadjetey** [comment]
I think I understand what your issue is. I usually just comment out the `url:` section in `_config.yml` file when debugging in localhost. No need to go through your long process every time. I hope that helps

**Comment by kenchowcn** [comment]
@nadjetey thanks, that's a good solution.
